### ISSUE TITLE
dataset preparation

### ISSUE THREAD

**Issue by YongtaoGE** [paulchhuang/bstro#2]
Hi, authors. thanks for great work!

Could this repository give more detailed instruction for preparing the proposed dataset RICH and training scripts, so that I can try to train the model?

**Comment by YongtaoGe** [comment]
By the way, the downloaded training images seems corrupted cannot uncompressed.

<img width="600" alt="截屏2022-07-17 下午9 18 09" src="https://user-images.githubusercontent.com/22744013/179396741-c310a739-e07a-404d-8872-9f5fdb241bb9.png">
.

**Comment by paulchhuang** [comment]
Hi, thanks for checking the repo!

We will release the full instruction of training within this month, including scripts for training/testing and processed database files (tsv format) for the experiments. Plz stay tuned. 

Btw, I remember there was a second post regarding broken downloading links. We looked into that and confirmed the links in the script are correct. Some FAQs for the downloading scripts:
- If it returns error msg `unexpected end of file`, copy paste the whole script to a terminal editor (vim, nano) and try again. 
- If the downloaded files are small, e.g., 6.X KB, it's most likely due to the wrong username/password.

**Comment by YongtaoGE** [comment]
@paulchhuang Thanks for your kindly reply. I am looking forward to the next version's release.

**Comment by paulchhuang** [comment]
FYI: the first version of training code is released. Plz follow the instructions [here](https://github.com/paulchhuang/bstro/blob/main/docs/EXP.md). Sorry for the delay.

**Comment by YongtaoGE** [comment]
Thanks for great work!
